modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/NovaMachina-Mods/NovaCore/issues"
license="CC BY-NC-SA 4.0"

[[mods]]
    modId="novacore"
    logoFile="logo.png"
    version="4.0.1"
    displayName="NovaCore"
    updateJSONURL="https://api.modrinth.com/updates/engHtMVe/forge_updates.json"
    authors="NovaMachina"
    description='''NovaCore is a library mod for all NovaMachina Mods'''

[[dependencies.novacore]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.23,22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.novacore]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

